# Generated by Django 3.1 on 2021-11-29 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foodlist', '0005_auto_20211129_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemToBuy',
            new_name='ShoppingList',
        ),
    ]
