# Generated by Django 3.1 on 2021-11-29 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foodlist', '0006_auto_20211129_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingListItem',
        ),
    ]
