# Generated by Django 3.1 on 2021-11-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodlist', '0009_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='foodlist.shoppinglist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
