# Generated by Django 3.1 on 2021-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0011_shoppinglist_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
