# Generated by Django 3.1 on 2021-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0014_productitem_productlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
