# Generated by Django 3.1 on 2021-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodlist', '0015_auto_20211201_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
