# Generated by Django 3.1 on 2021-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0019_shoppinglistitem_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
