# Generated by Django 3.1 on 2021-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0020_auto_20211202_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='in_shopping_list',
            field=models.BooleanField(default=False),
        ),
    ]
