# Generated by Django 3.1 on 2021-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodlist', '0021_productlist_in_shopping_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='in_shopping_list',
        ),
        migrations.AddField(
            model_name='product',
            name='default_amount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='in_shopping_list',
            field=models.BooleanField(default=False),
        ),
    ]
