# Generated by Django 3.1 on 2021-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0022_auto_20211202_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
